# Netlify configuration file

# This redirects all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Proxy API requests to the backend
[[redirects]]
  from = "/api/*"
  to = "https://digitext-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/webhooks/*"
  to = "https://digitext-backend.onrender.com/webhooks/:splat"
  status = 200
  force = true

# Build configuration
[build]
  command = "npm run build"
  publish = "dist"

# Site settings - specify the site name to match the previous deployment
[site]
  name = "dainty-babka-26b349"